### PR TITLE
add new relay

### PR DESCRIPTION
**Pull request by cercatrova21**

### CODE REVIEW

**Comment by MTG2000** [comment]
@johnsBeharry do you have any problems with adding this new relay??

**Comment by MTG2000** [comment]
Thanks!! @cercatrova21 

Any reasons behind recommending this specific relay??

Are you running it yourself?

**Comment by cercatrova21** [comment]
Yes it's my own hosted relay, that's the reason :)

**Comment by MTG2000** [comment]
> Yes it's my own hosted relay, that's the reason :)

Cool!!

**Pull request merged**
