### PR TITLE
Feat: generate story excerpt using AI service

### PR DESCRIPTION
**Pull request by MTG2000**
Model used: `GPT 3.5 Turbo`
Prompt used: 
"
The user will give you an article, & your job is to write a short description to it and to ALWAYS follow these rules:
        - The description should be short (just a few lines)
        - The description should be written in a way that will make people excited to read the full article. 
        - The description should be written as if the author of the article wrote it himself, not another person.
        - The output MUST always be a JSON object with one key: 'summary', where the value is the summary you generated.

Summarize this article which is surrounded by triple backticks:
  \`\`\`
  ${data.story.title}
  --------------------
  ${data.story.body}
  \`\`\`
"

@johnsBeharry 
If you have any additions to the prompt or updates, let me know.

I can include almost any piece of data from the story in the prompt (author name, tags, date, project name)

Of course, to get the most meaningful summary, we should only include the most relevant pieces of information.

I think: title, story body, project name if any. Should be enough.

 
**NOTE**
The description for a story will be generated ONLY once. When the story is first **published**.
Any later updates to the story will NOT trigger the ai service again.

### CODE REVIEW

**Comment by johnsBeharry** [comment]
tried testing with a social share debugger, and this is what shows for your story

https://deploy-preview-279--makers-bolt-fun-preview.netlify.app/story/sharing-my-fears-the-uncomfortable-journey-of-buildinpublic--23

Screenshot 2023-11-22 at 14 54 02

**Comment by MTG2000** [comment]
Hmm
Maybe it's an issue with the social preview tool.

I tried it on Telegram, & it seems to be working fine:
image

**Comment by johnsBeharry** [comment]
@MTG2000 here's an update to the prompt. let me know what you think.

```
Write an og:description meta tag for an article:
- Create a compelling summary in 1-2 sentences, max 110 characters.
- Begin with the most engaging part to attract clicks.
- Output as a JSON object with key 'summary' for the description.

Summarize this article which is surrounded by triple backticks:
\```
Title: ${data.story.title}

${data.story.body}
\```
```

**Comment by MTG2000** [comment]
Yeah, looks good.
I updated the prompt to this.

**Pull request merged**
