### PR TITLE
(WIP) Semantics and new navigation

### PR DESCRIPTION
**Pull request by johnsBeharry**
TODO

- [x] mobile navigation needs to get reworked
- [x] remove the large space above #content (need help from @MTG2000)
- [x] left nav links should work
- [x] show less of long comments. but still enough where it's useful to read
- [x] do not clip project names at 15 find out from @MTG2000
- [x] add write a story button in the navbar

### CODE REVIEW

**Comment by MTG2000** [comment]
@johnsBeharry 
Could you clarify more on points 3 & 5 in the tasks list above?

**Comment by johnsBeharry** [comment]
Four point number three basically make the navigation work. As we discussed this morning. 

For point number four in your first version you used a class which cuts off the text at a certain amount of limes. I couldn't remember which it was but I was thinking that we continue to show comments up to 5-7 lines

**Comment by MTG2000** [comment]
> I noticed that the names of projects in the postcard or are clipped after 15 characters. I didn't want to change it because I wasn't sure why.

Because maybe there are some projects names that are too long (longer than 15 chars)

**Comment by johnsBeharry** [comment]
Too long would be more than 15 characters though. What's the constrain that determines too  Uplong?

By the way this one shouldn't be blocking, you can ignore. it was mostly for me to explore and ask about.

**Comment by MTG2000** [comment]
@johnsBeharry You can review & test this PR now if you want.

**Comment by johnsBeharry** [comment]
Looks good to myself... for now.

**Pull request merged**
