### PR TITLE
Feature - List Your Project UI components and pages

### PR DESCRIPTION
**Pull request by MTG2000**

### CODE REVIEW

**Comment by barefoot-88** [comment]
@MTG2000 All in all, this is great work - particularly how fast you've pushed this out!! Here are a few things I noticed when flicking through on web + mobile. 

Before we begin, I just want to note that some of these issues appear when I inspect mobile size on my desktop, but on my actual mobile browser they aren't showing... 

I'll break it down by section so it's easier to follow...

## Navigation
**a). Tabs on mobile** : For some reason, when viewing the tabs on mobile there seem to be two small lines either side of the component... **_However, this doesn't show on the actual mobile view, so I'm wondering if it's just an issue with my inspect view... it also doesn't seem to be appearing now so maybe ignore this..._**
**b). Spacing of tabs on mobile**: Could we increase the spacing of the tabs on mobile to either 16px or 24px? That should create just enough space...

## Preview Card + CTAs
**a). Preview:** On mobile, can we please show the preview at the bottom with the CTAs either embedded or just above (same as now...)
**b). Preview avatar:** The alignment of the avatar image + text is off centred (to accommodate for two lines of text, however this issue will disappear if we set a character limit (below)). So could we please centre it so it doesn't look off balance?
**c). CTAs:** We don't seem to display a "Save for later" option. Is this because it's going to be difficult to save drafts of products? If it's doable, we could have "Next/Launch + Save for later" as the CTAs throughout, if the user tries to exit the page we say "Are you sure you want to lose your progress? CTAs = Continue / Save for later".

Screenshot 2022-08-17 at 15 26 09

Screenshot 2022-08-17 at 15 25 27

c). Custom error message: If the user tries to exit the journey with any progress, we should show a popup letting them know they will lose any progress if they continue. The CTAs should be "Continue" + "Cancel", or is possible... "Continue" + "Cancel" + "Save as draft". This can be a very simple centred modal...

## Product details
### General details
**a). Tagline:** I think we should cap the character limit of this to make sure makers keep it short. I've calculated the max on a single link for the preview card is about 35 characters. So we could do 32 to be safe. We should insert a "0 / 32" trailing text to the input-field so users know there is a limit...
**b). Description:** I noticed that the padding of this input field is different to the others. Could we reduce the padding so it matches the other fields?
**c). Input field size on mobile:** These ones feel a tad small to me, could they be the same as desktop? See comment below regarding Link input fields too. TLDR: same size Web + Mobile...

Screenshot 2022-08-17 at 15 22 42

### Links
**a). Input-field size:** The input fields here are larger than the ones in the Overview section above. Could we reduce them to match the size above? They otherwise look a tad intrusive...
**b). On mobile**, the size of these fields look about right... so maybe we can increase the size of the Overview text fields on mobile... They should be same size as web tbh...

### Category + Capabilities
**a). Spacing of rows:** Could these rows be as responsive as possible so that they go as close to the margin as possible? If there is a gap because the item would overrun off the card, then it can be put in the row below... but if there is space, it can go above. That way we're not wasting space when it could be used... Hopefully that makes sense...

Screenshot 2022-08-17 at 15 31 37

## Team
### Team section
Really great work! 
**a). Input field:** this doesn't seem to match the normal focused state of every other input field.. is there a reason for this? It should be same size, colours, states, etc...
**b). Spacing:** When inspecting on mobile, the component began to break a bit and didn't align well (see below). Could we have it so that if the component reaches a breaking point, the "Admin v" and 🗑 icon realign to a row below the avatar? To avoid this breaking point being reached unless it's on a tiny screen, we can put a limit on the characters shown of the makers name + job title. This is unlikely to occur for the name (unless they keep the original pub. key hash which is long), but more likely for a description. We can just use a "..." to indicate there is more to see.

Screenshot 2022-08-17 at 15 36 54

**Using ...**
Screenshot 2022-08-17 at 15 38 11

Screenshot 2022-08-17 at 15 38 32

**In case of required breaking*
Screenshot 2022-08-17 at 15 40 43

### Recruit
**a). Pill spacings:** Same issue as above (Category + Capabilities).

**Comment by MTG2000** [comment]
Hey @barefoot-88 
Thanks for the feedback 

I'll work on them very soon.
Just a few points to mention about some of the issues:

Navigation
a) okay 👍 
b) okay 👍 

Preview Card + CTAs
a) you mean that I should use the same card used now in desktop in mobile too??
b) okay 👍 
c) Well, the save drafts thing will only be possible after finishing the back-end work for this, and it will require some work both on FE & BE, so is this high priority to do now??
d) Regarding the prompt shown when the user tries to leave the page...
The prompt that is being shown here is native to the browser, and can't be customized unfourtunatly. 
I can only change the message being shown. But not the buttons for example.

Product Details
- General Details:
a) okay 👍 
b) okay 👍 
c) hmmm. they are exactly the same size on mobile and web 😅
I'm not reducing their size on mobile...

- Links
a) okay. I'll make them the same size as the overview inputs.
b) point (c) above

- Category + Capabilites
a) Yup, makes sense. And I've previously tried to do that. But this is a flex container, meaning that they are automatically layed out.
If an extra item can be added to a row it would be automatically. Sometimes this differnece is 1 or 2 px, but Then that would mean we would get inconsistent gaps.
I could make all the items the same size (grid) but I don't think they will look good. Or I can use a justify space between/around, but I also think that they wouldn't look better.

Team
- Team section
a) okay 👍 
b) okay 👍 

Recruit
a) talked about above

**Comment by Dolu89** [comment]
@MTG2000 Here are some problems I have seen while developing mutations for this feature
- While uploading an image (thumbnail, cover or screenshots), if user click on the next step before the image is fully loaded, image will not be saved in the form (but saved in HostedImage table)
- On "Browse images" from screenshots, all file types are available
- On updating project page, when multiple images has been uploaded before (on creation), clicking on the delete button of an image remove all images

**Comment by barefoot-88** [comment]
@MTG2000 @Dolu89 i was trying to preview this feature but didn't seem like the links were working...? 

What is the state of this feature release? Ideally we'd have this ready to go as soon as possible.

**Comment by Dolu89** [comment]
> @MTG2000 @Dolu89 i was trying to preview this feature but didn't seem like the links were working...?
> 
> What is the state of this feature release? Ideally we'd have this ready to go as soon as possible.

The PR #168 need to be reviewed and merged first in this branch

**Comment by MTG2000** [comment]
@barefoot-88 @johnsBeharry 
I've finished integrating the UIs with the backend API & finished adding most of the needed stuff for this feature to be ready.
I think you can start the QA review of this now 👍

**Comment by barefoot-88** [comment]
## QA feedback

### Project modal
- Avatar + Name, One-liner, Category should be centre aligned rather than to the top. It creates a strange gap at the bottom and disrupts my eye-line. 

Screenshot 2022-09-27 at 11 28 58

- Edit button is not in a good place as it disrupts the rest of the projects layout. This could be replaced with a small "✏️" icon (also used as the story's edit icon) which is placed next to the "X" icon in the top header.
- These icons "X" + "✏️" should also have a slight background (frosted) blur so they are easily distinguishable against the header image in the background.

Screenshot 2022-09-27 at 09 57 11

- About, Capabilities, Makers: We should stylise these headings as all caps, we will need to decrease the font size to Body/Paragraph 3 (12px). At the moment they look too big.

- Interaction: If the maker clicks the project name, it could take them to the website (link). This is so the maker can visit the project website/app and try it out. Open in new tab.

- Launch tag in header: I think it would be great to show if the project is 🔧 WIP or 🚀 Launched. If the project is launched, we could even include the date of launch on BOLT🔩FUN. E.g "🚀 Launched Feb 2nd, 2022".  Alternatively, we don't show the date as this might be an added field they eventually want to input.

Image 27-09-2022 at 11 37

**Mobile view**
- Avatar should overlap with the header as shown, otherwise there will be way too much white space. 

Screenshot 2022-09-27 at 10 03 52

**Comment by MTG2000** [comment]
> * Edit button is not in a good place as it disrupts the rest of the projects layout. This could be replaced with a small "✏️" icon (also used as the story's edit icon) which is placed next to the "X" icon in the top header.

Yup, agree.
But when I put it beside the "X" button, I'm getting the impression that the "X" button is a remove/delete button instead of "close" button.... (might be just me)

Maybe we can move the "X" button to the left in place of the "Launched" badge, and put the "launched" badge somewhere inside the modal.

**Comment by barefoot-88** [comment]
### Project tags
I think we want to make this UX as straightforward as possible. I was even a bit confused about this tag setting process.

- When a user inputs their project name, we could autofill the #tag input field with a suggested name (e.g "alby_123").
- The user can of course change this tag, or go with the one suggested.
- When creating a project, we can provide the maker with more content using our tooltip/information component. (see below).
- When editing a project, this tag field could have a "Change" button. This indicates it can be changed, but it puts an extra lock on the input field to avoid accidental or quick changes...
- When the maker clicks Change, a warning box pops up below the input field explaining the danger of changing this tag.
- Once the user clicks Save, the tag changes.

**ERRORS**
Makers could come across a number of errors with this input field. I can think of 3 at the moment:
- Tag unavailable. Try {suggestion-1}, {suggestion-2}
- Your username can only contain letters, numbers and '_’
- Your project tag must be shorter than 15 characters.

Screenshot 2022-09-27 at 13 19 41

**Comment by barefoot-88** [comment]
> > * Edit button is not in a good place as it disrupts the rest of the projects layout. This could be replaced with a small "✏️" icon (also used as the story's edit icon) which is placed next to the "X" icon in the top header.
> 
> Yup, agree. But when I put it beside the "X" button, I'm getting the impression that the "X" button is a remove/delete button instead of "close" button.... (might be just me)
> 
> Maybe we can move the "X" button to the left in place of the "Launched" badge, and put the "launched" badge somewhere inside the modal.

Hmm... personally I think it's ok but interesting point. @johnsBeharry any thoughts?

**Comment by barefoot-88** [comment]
One final thing @MTG2000 

When I'm adding my team, they  permissions dropdown (e.g Admin, Maker). This text is too large, it should be reduced by a Body size. I think the design uses Body 3 (12px).

**Comment by barefoot-88** [comment]
Just reviewing the changes. Couple of things...

i). Can we make this 1 paragraph, not 2. The next line should be a few suggestions (3).

Screenshot 2022-09-27 at 16 21 14

ii). Can we show real time error messages? Otherwise the maker has to wait until they submit their project and then get shown the error...

Screenshot 2022-09-27 at 16 24 06

iii). This shouldn't be an error. There should be a non-changeable Leading Text "#" as seen in the designs. Otherwise it becomes confusing if you need to type #alby, or just Alby, or even @alby ...

To make things less confusing as well, the pretext should read my_project_name

Screenshot 2022-09-27 at 16 27 51

**Comment by MTG2000** [comment]
Okays, I pushed these updates.

Just regarding point 2), the reason why it's done this way is mainly for performance reasons.
If the validation is triggered for each keystroke on any input for the form, the the performance might start lagging.

I changed the trigger now from 'submit' to 'blur then change', it should be better now.

**Comment by barefoot-88** [comment]
> If the validation is triggered for each keystroke on any input for the form, the the performance might start lagging.

Would it be possible to set logic from each keystroke to something like, if the user stops typing for longer than 2 seconds...?  That way they still get faster feedback but it doesn't lag as much.

> I changed the trigger now from 'submit' to 'blur then change', it should be better now.

I'll check it out 👍

**Comment by barefoot-88** [comment]
One final thing just with regards to error feedback. If an input field registers an error, the purple glow to signal the field is focused should turn red. If they begin typing again, or correct their error, it should revert to purple.

Screenshot 2022-09-28 at 10 12 49

**Comment by barefoot-88** [comment]
> One final thing @MTG2000
> 
> When I'm adding my team, they permissions dropdown (e.g Admin, Maker). This text is too large, it should be reduced by a Body size. I think the design uses Body 3 (12px).
> 
> We can also update the text in this information box to:
> 
> > **ℹ️ Onboard your team:** Make sure you onboard any other team members so they can help you manage this project and its development progress. To add them, they will first need to create a maker profile.
> 
> Screenshot 2022-09-27 at 13 38 40

Also, was this text size corrected, looks like it might have been missed.

**Comment by MTG2000** [comment]
Pushed an update that should fix these things 👍 

Btw, for the role dropdown, are you sure that 12px isn't too small??
(It might be just my eyes getting old)

**Pull request merged**
