### PR TITLE
A release that contains the roles-skills feature

### PR DESCRIPTION
**Pull request by MTG2000**

### CODE REVIEW

**Comment by barefoot-88** [comment]
Only thing I noticed was the line height above the : "ℹ️ Can't find a specific skill/role that you think should be here? You can ask for it to be added [here](https://github.com/peakshift/makers.bolt.fun/discussions/143)"

This line should be 1px high, not 2px as it currently is...

Screenshot 2022-09-01 at 16 15 07

Alternatively, we could use the info box as seen in the Submit Project journey (in Team ⚡️ section). It might make sense to use this more consistently within the platform for cards like this... I guess same could be used in the Linked Wallets 🔐 card

Screenshot 2022-09-01 at 16 17 32

**Comment by barefoot-88** [comment]
Nice work! Are we happy to merge?

**Comment by MTG2000** [comment]
@barefoot-88 
Merging is blocked until you or Johns approves this PR

**Comment by barefoot-88** [comment]
We'll release them in this order: 

- Introducing linked wallets 🔐
- Milestone 0.2 (which includes roles and skills)

We won't release roles and skills with a full article since it's a preliminary feature to tournaments etc. It also is fairly straight forward so doesn't require maybe as much detailed info as linked wallets etc

**Comment by MTG2000** [comment]
Yup, sounds good.

**Comment by barefoot-88** [comment]
The only thing I noticed on my final check was the button width on mobile, it doesn't quite fill the width of the container like it should do. You can see this correctly done on the "Basic Information" tab, but not Roles and Skills. Not the biggest error, so could merge without it done, but we should correct it at some point.

IMG_D9EF68771B01-1

Other than that I'm good to go!

**Review by barefoot-88 — APPROVED** [review]

**Pull request merged**
