### PR TITLE
Navigation component, redesigned profile edit, better carousel

### LINKED ISSUE #108: Redesign the edit state of maker profiles
## Issue
At the moment, maker profiles are very basic and allow users to edit their static profile data (e.g Name, description, etc). However, this will change in the coming months as we begin to add more **static*** and **dynamic*** information to the maker profile.

**Static information*:** Information that is attached to a maker profile does not regularly change. These are things like Name, Lightning Address, Avatar, Description, Timezone, Job Role, etc.
**Dynamic information*:** Information that is added to a maker profile over time as they become more active on the platform. These include Stories, Activity, Badges, Products (semi-dynamic as won't change too often). 

## Solution
As the maker profile becomes more complex and rich in data, makers will need a way to navigate the various elements of their profile - editing or viewing any information. For this to happen, I'd like to introduce a side navigation when the user accesses their profile's edit state. This state can be accessed by either:

- Going to their profile and clicking "Edit profile" button on their main profile card
- When the user clicks their avatar in the main page navigation bar (top right hand corner), a dropdown menu appears reading: Profile | Settings | Logout. If the user clicks "Settings", it should take them to the edit state of their profile. See #107 

Once the user sees the edit state of their profile, the page should be structure using our 3 column grid layout (same in Stories, etc). 
 
**Left column** ⬅️
User sees a page navigation card reading **"Edit maker profile"** with the menu options of **"👾 My profile"** (giving the edit access to their maker profile information) and **"⚙️ Preferences"** (giving them access to extra settings like Nostr comments, and later more). This card should be fixed to the top of the page when scrolling so the user can navigate between pages at any time.

**Centre column** ⬆️
In the centre column is the bulk of information shown as the user navigates through the various section of their profile and its settings. If the user has selected **👾 My profile** then it will show a card containing their profile information, if they've selected **⚙️ Preferences**, it will show a card outlining Nostr comments (v1), later to add more preferences and settings features (e.g Appearance, Notifications, etc).

**Right column** ➡️
In the right hand column is a card containing a preview state of the maker's profile (Avatar, name, job role, and description). Below this information is a **Save Changes** and **Cancel** CTAs. This card should be fixed to the top of the page when scrolling so the user can click "Save changes" at any time.

### Web view
**👾 My profile**
Screenshot 2022-07-29 at 11 50 37

**⚙️ Preferences**
Screenshot 2022-07-29 at 11 50 50

### Mobile view
Screenshot 2022-07-29 at 11 51 17

### PR DESCRIPTION
**Pull request by MTG2000**
Fixes #108, #107, #88, #87, #119

### CODE REVIEW

**Comment by MTG2000** [comment]
Fixes also these issues:
#91 #120

**Comment by barefoot-88** [comment]
@MTG2000 Here is some QA feedback to be implemented before we merge this PR. I'll break it up into sections and try to reference the issues where possible.

---

## Edit profile (Issue #108 )
### Left Column (Navigation)
- My profile (any information relating to the users profile)
- Settings & Preferences (Nostr, Linked Accounts (later), etc)
_This component is sticky whilst the user scrolls._

### Middle Column (Information)
- Selected page cards showing information (sometimes editable)

### Right Column (Profile Preview + Save/Cancel CTAs)
Within this card you have...
- Profile preview (Avatar, Name, Description, Role)
- CTAs (Save Changes, Cancel)
_This component is sticky whilst the user scrolls._

### Save Changes/Cancel button
- When the user enters this Edit profile state, the "Save Changes" button is disabled. Once the user makes a change to any element on that page, the button becomes enabled and the user can click it. 
- If the user makes a change and tries to navigate to another tab (i.e Settings & Preferences), a message pops up saying, "Are you sure you want to continue without saving your changes?" with two buttons "Save Changes" + "Continue without saving".
- If the user makes a change and clicks the "Cancel" button, a message appears with the same message as above, forcing the user to save or continue consciously and not accidentally lose progress.
- If the user clicks "Save Changes", the button should show a loading state indicating that an action is in progress. Once saved, this should be displayed in a message in the right hand column, giving the user an indication that its been saved and they can continue with another action. 
- If the user tries to save a change but there is an error (e.g Invalid Lightning Address), we should show this error message as "Unable to save changes, please review highlighted fields."

**No changes (Save disabled)**
Screenshot 2022-08-10 at 12 18 11

**Change made (Save enabled)**
Screenshot 2022-08-10 at 12 18 35

**Saving changes (In progress)**
Screenshot 2022-08-10 at 12 20 11

**Changes saved (Success)**
Screenshot 2022-08-10 at 12 21 09

**Changes failed (Error)**
Screenshot 2022-08-10 at 12 23 17

---

## Navigation (Issue #107 )
Please review the following QA changes to the navigation issue.

### Mobile
- "Connect ⚡️" sits in the primary navigation (top-right) when the menu is both closed and open. When logged in, this shows the users avatar.
- "Logout 👋" becomes list item when navigation menu is opened (user is logged in). It should sit at the bottom below Donate.
- For the time being, since we keep the primary CTA on the relevant page for mobile view (e.g "Write a Story"), we can remove this CTA in the open navigation menu.

Screenshot 2022-08-10 at 12 33 13


### Web
- When the user is not signed in, the Primary CTA in the top navigation bar is "Connect ⚡️", using an outline styled button (see design).
- Once the user is logged in, their avatar is displayed and the primary CTA is located next to it (top-right) in a purple filled button. This button changes based on which page the user is currently viewing (e.g Stories = "Write a Story", Apps = "Submit an app"). The only exception to this for the time being should be the Hackathons page, as a user doesn't need to be logged in to submit an event, in this scenario there would be no primary CTA in the top nav bar (unless the user isn't logged in, as we'd display the "Connect ⚡️" CTA).

**User not signed in**
Screenshot 2022-08-10 at 12 41 46

**User Signed In**
Screenshot 2022-08-10 at 12 42 20

---

## Categories Carousel (Apps page) (Issue #88 )
Please can we implement this carousel chevron as designed in #88 . As you can see, this should also be hovering there, rather than just showing up when the user hovers over it. 

**How it works**
We should implement it so that it is a single click in either direction. When normal, the chevron shows on the end of the row (right hand side), and when clicked it takes you to the end of the row (lying flush with the edge of the container). The chevron then appears on the left hand side so the user knows they can navigate back to the start position.

**Normal state**
Screenshot 2022-08-10 at 13 00 31

**After being clicked**
Chevron moves over to the left hand side. Final category item is flush to the side of the page.

Screenshot 2022-08-10 at 12 58 28

---

**Comment by barefoot-88** [comment]
@MTG2000 Please review...

## Navigation

**Mobile Menu**
- Only show "Logout" menu option when user's account is connected
- Remove extra padding (32px) from Menu list-items 
- Remove "Connect your lightning wallet" CTA
- Fix the shape of the Hackathons icon-circle (currently looks slightly stretched vertically...)

Screenshot 2022-08-10 at 16 07 05

**Web nav**
- Use more subtle outline button (border = 1px, colour = cool-grey/300, text colour = cool-grey/800)

Screenshot 2022-08-10 at 16 14 35

vs

Screenshot 2022-08-10 at 16 14 53

---

## Edit profile ⏳

... waiting for lnurl-auth response...

**Comment by MTG2000** [comment]
@barefoot-88 
Should be fixed now

**Review by johnsBeharry — CHANGES_REQUESTED** [review]
On the profile page, the Nostr section is still showing up.

Screenshot 2022-08-12 at 12 59 16

I noticed the route changed to Apps, @barefoot-88 we discuss changing it to the more generic "projects". Also we should try not to do too many changes to URLs because people might be sharing these pages and then they will be dead links. So lets make sure this is done properly, and just once more.

**Comment by barefoot-88** [comment]
A few things I noticed when clicking through on mobile... 

a). Profile names run off the edge of the screen.

image

b). Padding of profile components should be 16px, not 24px (always follow this rule on mobile)... 

- Profile details card 
- Makers' Stories card 
- Nostr Comments card (edit state)

c). Profile edit state: buttons should be vertically stacked 
- Save changes
- Cancel

image

d). Hottest projects page: should have the same margins, header card, etc as the other categories pages... 

image

**Comment by MTG2000** [comment]
@barefoot-88 @johnsBeharry 
Is there anything remaining in this PR before we can merge it?

**Comment by johnsBeharry** [comment]
@MTG2000 I'll do another review, but in the mean time is #109 dependent on this PR getting merged?

**Comment by MTG2000** [comment]
> is #109 dependent on this PR getting merged?

Nope, not really.

**Review by johnsBeharry — APPROVED** [review]

**Pull request merged**
